"""empty message

Revision ID: 1fd8871beaa9
Revises: 
Create Date: 2019-10-26 21:54:39.525271

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fd8871beaa9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('values',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fall_status', sa.Integer(), nullable=True),
    sa.Column('Accelerometer', sa.Float(), nullable=True),
    sa.Column('isTriggered', sa.Integer(), nullable=True),
    sa.Column('direction', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('values')
    # ### end Alembic commands ###
