"""empty message

Revision ID: d8d8b966002d
Revises: 
Create Date: 2019-06-30 01:33:01.857465

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8d8b966002d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('values',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fall_status', sa.Integer(), nullable=True),
    sa.Column('Accelerometer', sa.Float(), nullable=True),
    sa.Column('isTriggered', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('values')
    # ### end Alembic commands ###
