"""empty message

Revision ID: faa86a006c26
Revises: 
Create Date: 2020-02-22 14:04:10.333209

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'faa86a006c26'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('values',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('fall_status', sa.Integer(), nullable=True),
    sa.Column('Accelerometer_x', sa.Float(), nullable=True),
    sa.Column('Accelerometer_y', sa.Float(), nullable=True),
    sa.Column('Accelerometer_z', sa.Float(), nullable=True),
    sa.Column('isTriggered', sa.Integer(), nullable=True),
    sa.Column('direction', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('values')
    # ### end Alembic commands ###
